# 1. Задачи на программирование

## 1. Одиндватри
Рассмотрим последовательность натуральных чисел:
1,2,3,4,5,6,7,8,9,10,11,12,13,14, …Перевернем в ней каждое число. Получим последовательность:
1,2,3,4,5,6,7,8,9,01,11,21,31,41,…Запишем полученную последовательность слитно в виде одной строки:
1234567890111213141...

Напишите программу, которая выводит n-ую цифру полученной строки.

In [12]:
def solution(n):    
    l = 0
    for i in range(1, n + 1):
        rev = str(i)[::-1]
        l += len(rev)   
        if l>=n:
            return rev[n-l-1]
        
for i in range(1,10000):     
    if i % 1000 == 0:
        print(f"{i} = {solution(i)}")

1000 = 0
2000 = 0
3000 = 0
4000 = 2
5000 = 5
6000 = 7
7000 = 0
8000 = 2
9000 = 5


## 2. Угадайка
Определите по тестам условие задачи и напишите программу для ее решения.

Формат входных данных
На вход программе подается единственное натуральное число.

Формат выходных данных
Программа должна вывести единственное натуральное число.

In [27]:
def solution(n):
    return sum([int(d)+1 for d in n])

solution('123')

9

## 3. Зеркальный мир
Один странный доктор научился путешествовать в мир, который очень похож на наш, однако в нем все объекты отражены горизонтально. Все, что попадает в этот мир из реального, тоже «отзеркаливается», но доктор изобрел специальные ящики, содержимое которых остается в изначальном состоянии после переноса в новый мир.

Ящики выглядят как прямоугольники разных размеров, у которых нижняя и верхняя части обозначены символом _, а стенки — символом |. Содержимое ящиков состоит из букв латинского алфавита в произвольном регистре и цифр. Все пустое пространство на складе составляют символы .. Стенки, нижние и верхние части у ящиков могут совпадать.

Напишите программу, которая показывает, как будут выглядеть ящики после их переноса в зеркальное измерение.

In [42]:
import re


def solution(sn, test=None):
    n, m = list(map(int, sn.split(' ')))
    _box = re.compile(r'\w+', re.ASCII)
    if test:
        for t in test.splitlines():
            print(_box.sub(lambda x: x.group(0)[::-1], t)[::-1])


solution(
'9 9', '''.___.....
|123|__..
|456|AB|.
|___|CD|.
|XYZ|__|.
|___|....
......_..
._...|0|.
|_|..|_|.''')

.....___.
..__|123|
.|AB|456|
.|CD|___|
.|__|XYZ|
....|___|
.._......
.|0|..._.
.|_|..|_|


## 4. Скобки
Напишите программу, которая выводит все правильные скобочные выражения заданной длины, состоящие из круглых и квадратных скобок.

In [72]:
import itertools
def solution(n):
    return list(itertools.combinations(['()','[]'], n))

solution(4)

[]

# 5. Возрастающая подпоследовательность
Дана последовательность натуральных чисел. Напишите программу, которая из данной последовательности вычеркивает минимальное количество чисел так, чтобы оставшиеся шли в порядке возрастания.

In [198]:
# %%timeit
import numpy as np


def solution(ls):
    a = np.array(ls.split(' '), dtype=int)
    a=np.random.randint(100,size=20)
    print(a)
    d = np.ones(a.size, dtype=int)
    p = np.full(a.size, fill_value=-1, dtype=int)
    for i in range(d.size):
        for j in range(i):
            if a[j] < a[i]:
                d[i] = max(d[i], 1 + d[j])
                p[i] = j
    print(d)
    pos = np.argmax(d)
    print(pos)
    print(p[pos])
    d.fill(0)
    while pos != -1:
        d[pos] = 1
        pos = p[pos]

    
    return ' '.join(a[d.astype(bool)].astype(str))


solution('2 5 3 4 6 1')

[34 50 53 89 56 97  1 51 15 18  1 15 86 87 84 61 85 75 49 85]
[1 2 3 4 4 5 1 3 2 3 1 2 5 6 5 5 6 6 4 7]
19
18


'1 15 49 85'

In [199]:
# %%timeit
import numpy as np
# from scipy.stats import norm


def solution(ls):
    a = np.array(ls.split(' '), dtype=int)
    a=np.random.randint(100,size=100)
    print(a)
    d = np.diff(a, prepend=0)
    while np.any(d < 1):
        z = (d - d.mean()) / d.std()
#         se = d.std()/np.sqrt(d.size)
#         print(norm.ppf((1+0.95)/2)*se)
        
        se = np.ceil(np.abs(z).mean())
        print(z)
        print(se)
        a = a[np.abs(z) < se]
        d = np.diff(a, prepend=0)
    return ' '.join(a.astype(str))


solution('2 5 3 4 6 1')
# solution('1 3 5 2 4')

[40 63  5 92 18 28  5  4 66  7 38 24 37 59 87 32 38 29 40 86 19 39  9 14
 13 88 99 33 22 42 59 55 98 31 64 35 34 33 60 17 85 69 44 22  0 99 95 20
 49 98 67 97 60 13 48 67 14 49 69 64 54 92 91 13  2 21 17 82  0 35 76 22
 50 35 29  2 90 96  4 42 43 60 91 74 88 42 47 90 61 24 27 64 28 55 18 17
 55 44 38 57]
[ 0.99292338  0.56483062 -1.47490546  2.17647394 -1.87781629  0.23746557
 -0.59353802 -0.03953563  1.54692577 -1.50008739  0.76628604 -0.36690068
  0.31301135  0.53964869  0.69074026 -1.39935968  0.13673786 -0.24099104
  0.2626475   1.14401494 -1.7015428   0.48928484 -0.76981151  0.11155594
 -0.03953563  1.87429082  0.2626475  -1.67636087 -0.29135489  0.48928484
  0.41373906 -0.11508141  1.06846916 -1.7015428   0.81664989 -0.74462958
 -0.03953563 -0.03953563  0.66555833 -1.09717656  1.69801733 -0.41726453
 -0.64390187 -0.56835609 -0.56835609  2.47865707 -0.11508141 -1.90299822
  0.71592218  1.21956072 -0.79499343  0.74110411 -0.94608499 -1.19790426
  0.86701374  0.46410291 -1.34899582 

'4'

## 6. Одинаковые суммы
Напишите программу, которая проверяет, возможно ли разбить данный набор чисел на два непустых набора с одинаковой суммой.

In [82]:
# %%timeit
import numpy as np


def solution(ls):
    a = np.array(ls.split(), dtype=int)
    fsum = a.sum()
    sum2, m = np.divmod(fsum, 2)
    print(f"{fsum=}")
    if m == 1:
        return False
    s2, polusum, c, rem = sum2, 0, 0, fsum - sum2
    while s2 >= a.min():
        to_check = np.array([s2,rem])
#         polusum += np.sum(to_check[np.isin(to_check, a)]) * 2**c
        print(f"{s2=},{m=},{polusum=},{rem=},{c=}")
        print(to_check[np.isin(to_check, a)])

#         to_check = [s2, s2+m, s2-m]
        if np.sum(np.isin(to_check,a)) > 1:
            return True
        
        s2, m = np.divmod(rem, 2)
        rem -= s2
        
        c += 1
    return False


print(1)
print(solution('4 6'))
print(2)
print(solution('1 2 3 4 6'))
print(3)
print(solution('4 2 5 2 7 3 9 3 6 2 3 43 1 44 123 1'))
print(4)
print(solution('2 3 4 5'))
print(5)
print(solution('2 7 5'))

1
fsum=10
s2=5,m=0,polusum=0,rem=5,c=0
[]
False
2
fsum=16
s2=8,m=0,polusum=0,rem=8,c=0
[]
s2=4,m=0,polusum=0,rem=4,c=1
[4 4]
True
3
fsum=258
s2=129,m=0,polusum=0,rem=129,c=0
[]
s2=64,m=1,polusum=0,rem=65,c=1
[]
s2=32,m=1,polusum=0,rem=33,c=2
[]
s2=16,m=1,polusum=0,rem=17,c=3
[]
s2=8,m=1,polusum=0,rem=9,c=4
[9]
s2=4,m=1,polusum=0,rem=5,c=5
[4 5]
True
4
fsum=14
s2=7,m=0,polusum=0,rem=7,c=0
[]
s2=3,m=1,polusum=0,rem=4,c=1
[3 4]
True
5
fsum=14
s2=7,m=0,polusum=0,rem=7,c=0
[7 7]
True


In [39]:
np.isin([7,7], [2,7,5])


array([ True,  True])