# 1.1 Pandas

## Создайте pandas.Series из листа lst.

In [1]:
import pandas as pd
lst = list('zyxwvutsr')
ser = pd.Series(lst)
ser

0    z
1    y
2    x
3    w
4    v
5    u
6    t
7    s
8    r
dtype: object

## На основе листа lst и массива arr сформируйте словарь и cоздайте pandas.Series из получившегося словаря.

In [2]:
import numpy as np
import pandas as pd

lst = list('abced')
arr = np.arange(5)
pd.Series(arr, index=lst)

a    0
b    1
c    2
e    3
d    4
dtype: int64

## На вход функции solution подается серия ser. Преобразуйте ее в pandas.DataFrame таким образом, чтобы индекс стал отдельной колонкой датафрейма:

In [3]:
import pandas as pd
import numpy as np

def solution(ser):
    result = ser.reset_index()
    return result


ser = pd.Series([0, 1, 2, 3], index=list('abcd'))
solution(ser)

index  0
0     a  0
1     b  1
2     c  2
3     d  3

## Объедините два pandas.Series (s1, s2) таким образом чтобы получился pandas.DataFrame не используя конструктор!

In [4]:
import numpy as np
import pandas as pd

s1 = pd.Series(list('abced'))
s2 = pd.Series(np.arange(5))

pd.concat([s1, s2], axis=1)

0  1
0  a  0
1  b  1
2  c  2
3  e  3
4  d  4

## Объедините два pandas.Series (переменные s1, s2) таким образом чтобы получился pandas.DataFrame.Теперь используйте конструктор DataFrame.

In [5]:
import pandas as pd
import numpy as np

def solution():
    s1 = pd.Series(list('abced'))
    s2 = pd.Series(np.arange(5))
    result = pd.DataFrame(list(zip(s1, s2)), columns=['col1', 'col2'])
    return result


solution()

col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4

## Присвойте индексу pandas.Series имя 'characters':

In [6]:
import pandas as pd
import numpy as np

def solution():
    return pd.Series(list('abced'), name='characters')


solution()

0    a
1    b
2    c
3    e
4    d
Name: characters, dtype: object

## Получите элементы s1, которые не присутствуют в s2. Функция должна вернуть серию.

In [7]:
import pandas as pd

s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([4, 5, 6, 7, 8])

s1[~s1.isin(s2)]

0    1
1    2
2    3
dtype: int64

## Создайте новый pandas.Series из элементов, которые присутствуют только в одном из двух pandas.Series (переменные s1, s2). Если элемент присутствует в двух Series, то включать его не надо.

In [8]:
import pandas as pd
import numpy as np

s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([4, 5, 6, 7, 8])

res = pd.Series(np.union1d(s1, s2))
s12 = pd.Series(np.intersect1d(s1, s2))
res[~res.isin(s12)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

## На вход функции solution подаются данные в pandas.Series (переменная ser) рассчитайте:

* наименьшее значение
* 25 перцентиль
* медиану
* 75 перцентиль
* наибольшее значение

Все значения должны быть упакованы в серию.

In [10]:
import pandas as pd
import numpy as np

lst = [12.53904795, 5.68886327, 16.24734871, 9.60194377, 5.55134259,
       5.59100805, 10.09319475, 11.18922311, 10.06774274, 1.822353]

s1 = pd.Series(lst)
res = np.percentile(s1, [0, 25, 50, 75, 100])
print(res)

[ 1.822353    5.61547186  9.83484325 10.91521602 16.24734871]


## Определите сколько раз встречается каждое значение в исходном pandas.Series (переменная s). Функция должна вернуть серию с подсчитанным количеством каждого символа.

In [11]:
import pandas as pd

s = pd.Series(list('abdcbdhafceeabcahbcaedadaecbbbecafgh'))
s.value_counts()

a    8
b    7
c    6
e    5
d    4
h    3
f    2
g    1
Name: count, dtype: int64

# 1.2 Продолжаем прокачивать Pandas. Если ты еще не сбежал с первой тренировки и готов продолжать, тогда поехали :)

## Доработайте код таким образом, чтобы оставить только 2 наиболее встречающихся значения, а для остальных установите значение 'Yet another value'.

In [188]:
import pandas as pd

s = pd.Series(list('abdcbdhafceeabcahbcaedadaecbbbecafgh'))
r = s.value_counts().head(2)

for i, v in s.items():
    if not v in r:
        s[i] = 'Yet another value'

s

0                     a
1                     b
2     Yet another value
3     Yet another value
4                     b
5     Yet another value
6     Yet another value
7                     a
8     Yet another value
9     Yet another value
10    Yet another value
11    Yet another value
12                    a
13                    b
14    Yet another value
15                    a
16    Yet another value
17                    b
18    Yet another value
19                    a
20    Yet another value
21    Yet another value
22                    a
23    Yet another value
24                    a
25    Yet another value
26    Yet another value
27                    b
28                    b
29                    b
30    Yet another value
31    Yet another value
32                    a
33    Yet another value
34    Yet another value
35    Yet another value
dtype: object

## Разбейте все значения из pandas.Series (переменная s1) на 3 интервала равного размера. Функция должна вернуть серию.

In [187]:
import pandas as pd

s1 = pd.Series(reversed(range(0, 10)))
pd.qcut(s1, 3)

0       (6.0, 9.0]
1       (6.0, 9.0]
2       (6.0, 9.0]
3       (6.0, 9.0]
4       (3.0, 6.0]
5       (3.0, 6.0]
6       (3.0, 6.0]
7    (-0.001, 3.0]
8    (-0.001, 3.0]
9    (-0.001, 3.0]
dtype: category
Categories (3, interval[float64, right]): [(-0.001, 3.0] < (3.0, 6.0] < (6.0, 9.0]]

## Преобразуйте pandas.Series (переменная s1) в pandas.DataFrame размером 2 х 5.

In [186]:
import pandas as pd
import numpy as np

s1 = pd.Series(range(0, 10))
pd.DataFrame(np.array(s1).reshape(2, 5))

0  1  2  3  4
0  0  1  2  3  4
1  5  6  7  8  9

## Найдите индексы значений, которые кратны 2. Функция solution должна вернуть numpy массив:

In [22]:
import pandas as pd
import numpy as np

s1 = pd.Series([5, 10, 2, 3, 9, 12, 1])
np.argwhere(s1.to_numpy() % 2 == 0)

array([[1],
       [2],
       [5]])

## Создайте новый pandas.Series из элементов, которые находятся по индексам: 0, 7, 12, 15, 19. 

In [182]:
import pandas as pd

s1 = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))

s1.take([0, 7, 12, 15, 19])

0     a
7     h
12    m
15    p
19    t
dtype: object

## Преобразуйте элементы pandas.Series (переменная s1) из строк в даты. Функция solutionдолжна вернуть серию.



In [183]:
import pandas as pd

s1 = pd.Series(['01 Jan 2022', '02-02-2022', '20220303', '2022/04/04', '2022-05-05', '2022-06-06T12:20'])
pd.to_datetime(s1, format='mixed')

0   2022-01-01 00:00:00
1   2022-02-02 00:00:00
2   2022-03-03 00:00:00
3   2022-04-04 00:00:00
4   2022-05-05 00:00:00
5   2022-06-06 12:20:00
dtype: datetime64[ns]

## Объект pandas.Series (переменная s1) содержит некоторые числовые значения. Для значений хранящихся в s2 определите индексы под которыми они хранятся  в s1. Функция должна вернуть список (python list):



In [28]:
import pandas as pd

s1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
s2 = pd.Series([1, 3, 10, 13])

print(s1[s1.isin(s2)].sort_values().index.to_list())

[5, 4, 0, 8]


## Даны следующие ряды данных:

s_forecast - ряд прогнозных значений

s_real - ряд фактических значений

 

Вычислите среднеквадратичную ошибку.



In [29]:
import pandas as pd

s_forecast = pd.Series(range(10))
s_real = pd.Series(reversed(range(10)))

print(((s_forecast - s_real)**2).mean())

33.0


## Измените первый символ каждого слова на верхний регистр.

In [185]:
import pandas as pd
s1 = pd.Series(['the', 'weather', 'is', 'fine'])

s1.str.capitalize()

0        The
1    Weather
2         Is
3       Fine
dtype: object

## Подсчитайте количество символов в каждом слове. Функция solution должна вернуть серию.

In [31]:
import pandas as pd

s1 = pd.Series(['the', 'weather', 'is', 'fine'])

print(s1.str.len())

0    3
1    7
2    2
3    4
dtype: int64


# 1.3

## Вытяните день месяца, номер недели, день года и день недели из серии (s1)

In [4]:
import pandas as pd
import numpy as np

s1 = pd.Series(['05 Jan 2021', '02-04-2021', '20210403', '2021/06/04', '2021-03-05', '2021-03-06T12:20'])
s1 = pd.to_datetime(s1, format="mixed")
print(f"Date:  {list(s1.dt.day.values)}")
print(f'Week number:  {list(s1.dt.isocalendar().week.values)}')
print(f'Day number of year:  {list(s1.dt.dayofyear.values)}')
print(f'Day of week:  {list(s1.dt.day_name().values)}')

Date:  [np.int32(5), np.int32(4), np.int32(3), np.int32(4), np.int32(5), np.int32(6)]
Week number:  [np.uint32(1), np.uint32(5), np.uint32(13), np.uint32(22), np.uint32(9), np.uint32(9)]
Day number of year:  [np.int32(5), np.int32(35), np.int32(93), np.int32(155), np.int32(64), np.int32(65)]
Day of week:  ['Tuesday', 'Thursday', 'Saturday', 'Friday', 'Friday', 'Saturday']


## Измените даты лежащие в серии (s1) таким образом чтобы они начинались с 10-го числа соответствующего месяца.

In [6]:
import pandas as pd
import numpy as np

s1 = pd.Series(['Jan 2022', 'Feb 2022', 'Mar 2022'])

s2 = pd.to_datetime(s1, format="mixed")
print(s2+pd.Timedelta(days=9))

0   2022-01-10
1   2022-02-10
2   2022-03-10
dtype: datetime64[ns]


## Из серии (s1) вытяните слова, содержащие не менее 2 гласных.

In [9]:
import pandas as pd
import numpy as np
import re

s1 = pd.Series(['Apple', 'Orange', 'Plan', 'Sky', 'Money'])
print(s1[s1.str.count('[euioa]', flags=re.I) > 1])

0     Apple
1    Orange
4     Money
dtype: object


## Извлеките корректные почтовые адреса из серии (s1). Используйте pattern для этой задачи.

In [20]:
import pandas as pd
import numpy as np
import re

s1 = pd.Series(['teach pandas at stepik.com', 'help@stepik.com', 'user@t.co', 'lovepandas@google.com'])

pattern = '[\\w_-]+@[\\w_-]+\\.[\\w]{2,4}'
print(s1[s1.str.match(pattern, re.I)])

1          help@stepik.com
2                user@t.co
3    lovepandas@google.com
dtype: object


## Вычислите среднее значение веса каждого фрукта.

In [21]:
import pandas as pd
import numpy as np

fruit_list = ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']
weights_list = [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]

fruits = pd.Series(fruit_list)
weights = pd.Series(weights_list)
print(weights.groupby(fruits).mean())

apple     6.0
banana    4.0
carrot    5.8
dtype: float64


## Вычислить евклидово расстояние между рядами (точками) X и Y

In [23]:
import pandas as pd
import numpy as np

X = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
Y = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])


print((sum((X-Y)**2)**0.5))

18.16590212458495


## В серии (s1) находятся даты с 1 по 8 января 2022 года. Однако некоторые даты и значения к датам пропущены. Сделайте так, чтобы все отсутствующие даты отображались и заполнялись значением из предыдущей даты.

In [27]:
import pandas as pd
import numpy as np

def solution():
    s1 = pd.Series([1, 10, 3, np.nan], index=pd.to_datetime(['2022-01-01', '2022-01-03', '2022-01-06', '2022-01-08']))
    s2 = pd.Series(s1, index=pd.date_range("2022-01-01", periods=8, freq="D"))
    return s2.ffill()


solution()

2022-01-01     1.0
2022-01-02     1.0
2022-01-03    10.0
2022-01-04    10.0
2022-01-05    10.0
2022-01-06     3.0
2022-01-07     3.0
2022-01-08     3.0
Freq: D, dtype: float64

## Отредактируйте название колонок датафрейма (df) следующим образом:

1. user -> user_name

2. все точки в названии колонок заменить нижним подчёркиванием

In [33]:
import pandas as pd
import numpy as np

def solution():
    df = pd.DataFrame(data={'user': ['Ivan', 'Petr', 'Alex'], 'user.balance': [
                      500, 200, 0], 'user.age': [34, 25, 18], 'user.group': ['A', 'B', 'A']})
    df.rename(columns={'user': 'user_name'}, inplace=True)
    df.rename(columns=lambda x: x.replace('.', '_'), inplace=True)

    return df


solution()

user_name  user_balance  user_age user_group
0      Ivan           500        34          A
1      Petr           200        25          B
2      Alex             0        18          A

## Проверьте, имеются ли пропущенные значения в датафрейме (df). Если в строке датафрейма есть хотя-бы одно пропущенное значение - верните True иначе False.

In [35]:
import pandas as pd
import numpy as np

def solution():
    df = pd.DataFrame(data={'user': ['Ivan', 'Petr', 'Alex'], 'user.balance': [
                      500, None, 0], 'user.age': [34, 25, 18], 'user.group': ['A', 'B', 'A']})
    result = df.isnull().any(axis=1)
    return result


solution()

0    False
1     True
2    False
dtype: bool

# 1.4

## Подсчитайте количество пропущенных значений в каждом столбце.

In [37]:
import pandas as pd
import numpy as np

df = pd.DataFrame(data={'user': ['Ivan', 'Petr', 'Alex', 'Den'], 'user.balance': [
                  500, None, 0, None], 'user.age': [34, None, 18, 43], 'user.group': ['A', 'B', 'A', 'B']})
df.isna().sum()

user            0
user.balance    2
user.age        1
user.group      0
dtype: int64

## Замените отсутствующие значения в столбцах user.speed и user.bag_weight их соответствующими средними значениями.

In [64]:
import pandas as pd
import numpy as np

df = pd.DataFrame(data={'user': ['Ivan', 'Petr', 'Alex', 'Den'], 'user.speed': [
                  40, None, 42, 35], 'user.bag_weight': [8, None, 2, 4]})

print(df[['user.speed', 'user.bag_weight']].apply(lambda x: x.fillna(x.mean()), axis=0))

   user.speed  user.bag_weight
0        40.0         8.000000
1        39.0         4.666667
2        42.0         2.000000
3        35.0         4.000000


## Используйте метод apply, чтобы заменить отсутствующие значения в user.speed средним значением столбца, а в user.bag_weight — медианой столбца.

In [67]:
import pandas as pd
import numpy as np

df = pd.DataFrame(data={'user': ['Ivan', 'Petr', 'Alex', 'Den'], 'user.speed': [
                  40, None, 42, 35], 'user.bag_weight': [8, None, 2, 4]})
df[['user.speed', 'user.bag_weight']] = df.apply(
    {'user.speed': lambda x: x.fillna(x.mean()), 'user.bag_weight': lambda x: x.fillna(x.median())})
df

user  user.speed  user.bag_weight
0  Ivan        40.0              8.0
1  Petr        39.0              4.0
2  Alex        42.0              2.0
3   Den        35.0              4.0

## Поменяйте столбцы А и Е местами в датафрейме:

In [71]:
import pandas as pd
import numpy as np


df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

df[list('ebcda')]

e   b   c   d   a
0   4   1   2   3   0
1   9   6   7   8   5
2  14  11  12  13  10
3  19  16  17  18  15

## Поменяйте порядок столбцов в датафрейме от Е до А.

In [73]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
df[list('edcba')]

e   d   c   b   a
0   4   3   2   1   0
1   9   8   7   6   5
2  14  13  12  11  10
3  19  18  17  16  15

## Выведите на экран строки датафрейма с шагом 2.

In [79]:
import pandas as pd
import numpy as np

df = pd.DataFrame(data={'user': ['Ivan', 'Petr', 'Alex', 'Den', 'Viktor'], 'user.speed': [
                  40, None, 42, 35, 60], 'user.bag_weight': [8, None, 2, 4, 19]})

df[::2]

user  user.speed  user.bag_weight
0    Ivan        40.0              8.0
2    Alex        42.0              2.0
4  Viktor        60.0             19.0

## Создайте составной индекс на основе колонок user и user.number для датафрейма:



In [88]:
import pandas as pd
import numpy as np

df = pd.DataFrame(data={'user': ['Ivan', 'Petr', 'Alex', 'Den', 'Viktor'], 'user.number': [
                  '222-333', None, '222-555', '222-666', '222-777'], 'user.speed': [40, None, 42, 35, 60], 'user.bag_weight': [8, None, 2, 4, 19]})

df.fillna({"user.number": "missing"}, inplace=True)
df.index = df.apply(lambda x: f"{x['user']}_{x['user.number']}", axis=1)
df

user user.number  user.speed  user.bag_weight
Ivan_222-333      Ivan     222-333        40.0              8.0
Petr_missing      Petr     missing         NaN              NaN
Alex_222-555      Alex     222-555        42.0              2.0
Den_222-666        Den     222-666        35.0              4.0
Viktor_222-777  Viktor     222-777        60.0             19.0

## Для столбца А найдите индекс строки в которой находится второе наибольшее значение.



In [92]:
import pandas as pd
import numpy as np

df = pd.DataFrame([[16, 24, 29], [1, 10, 16], [26, 21, 10], [3, 3, 8], [6, 17, 17], [2, 25, 14],
                  [9, 13, 21], [27, 24, 17], [19, 29, 1], [20, 24, 6]], columns=list('abc'))

print(df.sort_values(by=["a"]).index[-2])

2


## Выведите последние две строки датафрейма, сумма ячеек которых больше 100.

In [93]:
import pandas as pd
import numpy as np

df = pd.DataFrame([[23, 33, 16, 35],
                   [24, 20, 13, 10],
                   [32, 33, 30, 28],
                   [13, 32, 36, 18],
                   [25, 27, 31, 10],
                   [35, 13, 36, 21],
                   [32, 32, 25, 17],
                   [34, 24, 23, 19]])

print(df[df.sum(axis=1) > 100].tail(2))

    0   1   2   3
5  35  13  36  21
6  32  32  25  17


# 1.5

## Выведите на экран сводку основной информации о датафрейме. 

In [94]:
import pandas as pd
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

#### YOUR ANSWER BELOW THIS LINE ######
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


## Выведите на экран первые три записи датафрейма.

In [96]:
import pandas as pd
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

#### YOUR ANSWER BELOW THIS LINE ######
df.head(3)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

## Выведите на экран данные, которые хранятся в строках [3, 4, 8] и колонках ['animal', 'age']

In [103]:
import pandas as pd
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

#### YOUR ANSWER BELOW THIS LINE ######
df[['animal', 'age']].iloc[[3, 4, 8]]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

## Выберите только те строки, в которых количество посещений (visits) больше 2.

In [106]:
import pandas as pd
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

#### YOUR ANSWER BELOW THIS LINE ######
df[df['visits'] > 2]

animal  age  visits priority
b    cat  3.0       3      yes
d    dog  NaN       3      yes
f    cat  2.0       3       no

## Выберите строки датафрейма  в которых animal = cat, а age < 3.

In [108]:
import pandas as pd
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

#### YOUR ANSWER BELOW THIS LINE ######
df.query("animal=='cat' & age<3")

animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

## В строке f замените значение в колонке age на 1.5

In [109]:
import pandas as pd
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

#### YOUR ANSWER BELOW THIS LINE ######
df.loc["f", "age"] = 1.5
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

## Посчитайте итоговое количество посещений (visits)

In [111]:
import pandas as pd
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

#### YOUR ANSWER BELOW THIS LINE ######
print(int(df["visits"].sum()))

19


## Посчитайте средний возраст каждого вида животного (animal)

In [113]:
import pandas as pd
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

#### YOUR ANSWER BELOW THIS LINE ######
df.groupby('animal')['age'].mean()

animal
cat      2.5
dog      5.0
snake    2.5
Name: age, dtype: float64

## Отсортируйте датафрейм по столбцу age в порядке убывания, а затем по столбцу visits в порядке возрастания. 

In [115]:
import pandas as pd
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

#### YOUR ANSWER BELOW THIS LINE ######
df.sort_values(['age', 'visits'], ascending=[False, True])

animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  2.0       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

## Столбец priority содержит строковые значения yes и no. Замените их на булевы True и False

In [117]:
import pandas as pd
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

#### YOUR ANSWER BELOW THIS LINE ######
df['priority'] = (df['priority'] == 'yes')
df

animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
d    dog  NaN       3      True
e    dog  5.0       2     False
f    cat  2.0       3     False
g  snake  4.5       1     False
h    cat  NaN       1      True
i    dog  7.0       2     False
j    dog  3.0       1     False

## Определите средний возраст для каждого типа животного и количества посещений.

In [119]:
import pandas as pd
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

#### YOUR ANSWER BELOW THIS LINE ######
df.pivot_table(index='animal', columns='visits', values='age', aggfunc='mean')

visits    1    2    3
animal               
cat     2.5  NaN  2.5
dog     3.0  6.0  NaN
snake   4.5  0.5  NaN

# 1.6

## Вычтите среднее значение строки из каждого элемента в строке.

In [121]:
import pandas as pd
import numpy as np

df = pd.DataFrame([[0.020448, 0.456925, 0.992258], [0.743399, 0.555486, 0.089364], [0.094699, 0.283184, 0.216221]])
df.apply(lambda x: x-df.mean(axis=1))

0         1         2
0 -0.469429 -0.032952  0.502381
1  0.280649  0.092736 -0.373386
2 -0.103336  0.085149  0.018186

## В каком столбце чисел сумма наименьшая? Выведите на экран название этого столбца.

In [122]:
import pandas as pd
import numpy as np

df = pd.DataFrame([[0.020448, 0.456925, 0.992258], [0.743399, 0.555486, 0.089364],
                  [0.094699, 0.283184, 0.216221]], columns=list('abc'))

print(df.sum().sort_values().index[0])

a


## Как подсчитать, сколько уникальных строк имеет датафрейм (т. е. игнорировать все повторяющиеся строки)?

In [125]:
import pandas as pd
import numpy as np

df = pd.DataFrame([[0.020448, 0.456925, 0.992258], [0.743399, 0.555486, 0.089364], [
                  0.020448, 0.456925, 0.992258], [0.094699, 0.283184, 0.216221]], columns=list('abc'))

print(df.duplicated(keep=False).sum())

2


## Имеется датафрейм состоящий из 10 столбцов чисел с плавающей запятой. Ровно 5 записей в каждой строке являются значениями NaN. Для каждой строки датафрейма найдите столбец, содержащий третье значение NaN.

In [128]:
import pandas as pd
import numpy as np

nan = np.nan

data = [[0.04, nan, nan, 0.25, nan, 0.43, 0.71, 0.51, nan, nan],
        [nan, nan, nan, 0.04, 0.76, nan, nan, 0.67, 0.76, 0.16],
        [nan, nan, 0.5, nan, 0.31, 0.4, nan, nan, 0.24, 0.01],
        [0.49, nan, nan, 0.62, 0.73, 0.26, 0.85, nan, nan, nan],
        [nan, nan, 0.41, nan, 0.05, nan, 0.61, nan, 0.48, 0.68]]

columns = list('abcdefghij')

df = pd.DataFrame(data, columns=columns)
df.apply(lambda x: x[x.isna()].index[2], axis=1)

0    e
1    c
2    d
3    h
4    d
dtype: object

## Датафрейм содержит колонку grps (название некоторой группы) и колонку целочисленных значений vals.  Для каждой группы найдите сумму трех наибольших значений.

In [130]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12, 345, 3, 1, 45, 14, 4, 52, 54, 23, 235, 21, 57, 3, 87]})

df.groupby('grps').agg(lambda x: x.sort_values(ascending=False).head(3).sum()).squeeze()

grps
a    409
b    156
c    345
Name: vals, dtype: int64

## Датафрейм df имеет два целочисленных столбца «A» и «B». Значения в «A» находятся в диапазоне от 1 до 100 (включительно).

Для каждой группы из 10 последовательных целых чисел в столбце А (т. е. (0, 10], (10, 20], ...) вычислите сумму соответствующих значений в столбце B.

In [136]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.RandomState(8765).randint(1, 101, size=(100, 2)), columns=["A", "B"])

df['B'].groupby(pd.cut(df['A'], bins=pd.interval_range(start=0, end=100, freq=10)), observed=False,).sum()

A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
Name: B, dtype: int64

## Создайте список индексов столбцов и строк для 3 самых больших значений в предлагаемом датафрейме.

In [141]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.RandomState(30).randint(1, 101, size=(8, 8)))

df.unstack().sort_values().tail(3).index.to_list()

[(5, 7), (6, 4), (2, 5)]

## Создайте новый столбец patched_vals, который содержит те же значения, что и vals, но отрицательные значения заменить средним значением группы.

In [151]:
import pandas as pd
import numpy as np

df = pd.DataFrame({"vals": np.random.RandomState(31).randint(-30, 30, size=15),
                   "grps": np.random.RandomState(31).choice(["A", "B"], 15)})

df['patched_vals'] = df.groupby('grps')['vals'].transform(lambda x: np.where(x < 0, x[x > 0].mean(), x))
df

vals grps  patched_vals
0    -12    A          13.6
1     -7    B          28.0
2    -14    A          13.6
3      4    A           4.0
4     -7    A          13.6
5     28    B          28.0
6     -2    A          13.6
7     -1    A          13.6
8      8    A           8.0
9     -2    B          28.0
10    28    A          28.0
11    12    A          12.0
12    16    A          16.0
13   -24    A          13.6
14   -12    A          13.6

## Найдите сумму всех значений, которые указаны для среды (Wednesday)

In [152]:
import pandas as pd
import numpy as np


dti = pd.date_range(start='2021-01-01', end='2021-12-31', freq='B')
s = pd.Series(np.random.RandomState(30).rand(len(dti)), index=dti)

print(s[s.index.dayofweek == 2].sum())

23.508792429234397


## Для каждого месяца найдите среднее значение.

In [155]:
import pandas as pd
import numpy as np

dti = pd.date_range(start='2021-01-01', end='2021-12-31', freq='B')
s = pd.Series(np.random.RandomState(30).rand(len(dti)), index=dti)

s.groupby(pd.Grouper(freq='ME')).mean()

2021-01-31    0.507726
2021-02-28    0.462692
2021-03-31    0.478605
2021-04-30    0.564210
2021-05-31    0.387735
2021-06-30    0.451999
2021-07-31    0.541958
2021-08-31    0.553241
2021-09-30    0.507650
2021-10-31    0.453517
2021-11-30    0.490528
2021-12-31    0.495812
Freq: ME, dtype: float64

# 1.7

## Превратите датафрейм в квадрат с максимально возможной длиной стороны n, убрав отрицательные значения. При необходимости удалите наименьшие значения. Порядок положительных чисел в результате должен оставаться таким же, как и в оригинале.

In [158]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.RandomState(30).randint(-20, 50, 100).reshape(10, -1))


df = df.to_numpy(dtype="float64")
df = df[df > 0]
n = int(np.floor(len(df)**0.5))
print(df[sorted(df.argsort()[-n**2:])].reshape(n, n))

[[17. 17. 25. 25. 33. 26. 21. 45.]
 [29. 25. 41. 15. 42. 26. 25. 44.]
 [42. 30. 13. 35. 38. 37. 24. 17.]
 [37. 19. 13. 27. 19. 16. 20. 34.]
 [49. 10. 29. 32. 24. 41. 14. 23.]
 [40. 31. 21. 36. 19. 13.  8. 38.]
 [25. 28. 35. 25. 11.  9. 24.  9.]
 [31. 35. 32. 41. 19. 10. 24. 27.]]


## Поменяйте местами строки 1 и 2

In [161]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.arange(25).reshape(5, -1))

df.index = [0, 2, 1, 3, 4]
df.sort_index()

0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24

## Измените порядок строк датафрейма таким образом, чтобы последние стали первыми, а первые последними (reverse).

In [163]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.arange(25).reshape(5, -1))

df.reindex(df.index.sort_values(ascending=False))

0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4

## Выполните one-hot encoding для столбца А и добавьте результат к датафрейму

In [165]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.arange(25).reshape(5, -1), columns=list('abcde'))

pd.concat([pd.get_dummies(df['a']), df.reindex(columns=list('bcde'))], axis=1)

0      5     10     15     20   b   c   d   e
0   True  False  False  False  False   1   2   3   4
1  False   True  False  False  False   6   7   8   9
2  False  False   True  False  False  11  12  13  14
3  False  False  False   True  False  16  17  18  19
4  False  False  False  False   True  21  22  23  24

## Создайте новый столбец таким образом, чтобы каждая строка содержала номер наиболее удалённой строки-записи по евклидову расстоянию.

In [169]:
import pandas as pd
import numpy as np

def solution(df):
    def foo(x):
        return df.apply(lambda y: int(round(np.sqrt(np.sum((x-y)**2)))), axis=1)
    _df = df.apply(foo, axis=1)
    df['nearest_row'] = _df.idxmax()
    df['dist'] = _df.max()

    return df


df = pd.DataFrame(np.random.RandomState(30).randint(1, 100, 40).reshape(
    10, -1), columns=list('pqrs'), index=list('abcdefghij'))
solution(df)

p   q   r   s nearest_row  dist
a  38  38  46  46           f    61
b  13  24   3  54           j   100
c  18  47   4  42           j    97
d   8  66  50  46           f    96
e  62  36  19  19           j   103
f  77  17   7  63           j   107
g  28  47  46  65           h    71
h  63  12  16  24           j   110
i  14  51  34  56           f    77
j  29  59  92  79           h   110

## Определите максимально возможное значение корреляции каждого столбца по сравнению с другими столбцами датафрейма.

In [170]:
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.RandomState(25).randint(1, 100, 80).reshape(
    8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))

_df = df.corr().round(2).abs()
print(_df[_df < 1].max().to_numpy())

[0.77 0.64 0.77 0.85 0.62 0.85 0.62 0.67 0.44 0.62]


## Определите отношение минимума к максимуму для каждой строки.

In [172]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.RandomState(25).randint(1, 100, 80).reshape(8, -1))

df.min(axis=1)/df.max(axis=1)

0    0.054945
1    0.022222
2    0.023529
3    0.022989
4    0.030303
5    0.032967
6    0.170455
7    0.164835
dtype: float64

## Создайте новый столбец penultimate (с англ. предпоследний), который имеет второе по величине значение каждой строки датафрейма:

In [174]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.RandomState(25).randint(1, 100, 80).reshape(8, -1))

df['penultimate'] = df.apply(lambda x: x.nlargest(2).min(), axis=1)
df

0   1   2   3   4   5   6   7   8   9  penultimate
0   5  63  91  16  62  24  45  51   9  29           63
1   5  90  32  70   2  40   4  89  56   4           89
2  85  46   4   2  23  32  49  48  74  17           74
3  51  86  37  10  33  11  61  48   2  87           86
4  92  50  19  93  37  99  31  39   3   6           93
5  58  74  23  12   3  44  91  62  85  84           85
6  75  18  15  84  38  88  51  52  15  72           84
7  63  91  16  15  77  40  89  47  54  30           89

## Нормализуйте все столбцы датафрейма, вычитая среднее значение столбца и разделив на стандартное отклонение:

In [181]:
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.RandomState(20).randint(1, 100, 80).reshape(8, -1))

((df-df.mean(axis=0))/df.std(axis=0)).round(2)

0     1     2     3     4     5     6     7     8     9
0  1.47 -1.13  1.31 -0.59  1.38 -1.00 -1.27  0.98 -0.46  0.59
1 -0.23  1.07 -0.50  1.08  1.38 -0.47  1.03 -0.97  0.72 -1.08
2 -1.05  1.12 -1.62 -0.65 -0.69  1.07  0.12 -0.67 -1.02  0.68
3  1.02  0.12  0.72  1.02  0.50  1.67 -0.83 -1.17 -0.93  0.71
4 -0.71 -1.45  0.72 -0.92  0.12 -0.78 -1.34  1.11  1.55  0.23
5  0.89  0.50 -0.86 -0.10 -0.87  0.70  0.85 -0.71 -0.58  1.26
6 -0.26  0.58 -0.43  1.34 -0.95 -0.72  0.56  0.22 -0.46 -1.14
7 -1.14 -0.80  0.66 -1.18 -0.87 -0.47  0.89  1.21  1.19 -1.26

# 1.8

## Для вас подготовлен датафрейм содержащий имена пользователей и их теги. Ваша задача заключается в том чтобы вытянуть самый первый тег из списка и сформировать отдельную колонку:

In [5]:
import pandas as pd

initial_df = pd.DataFrame({'user_name': ['Ivan 007', 'Petr 911', 'Nikolay 112'], 'user_tags': [
                          "['sport', 'law', 'cars']", "['cars', 'law', 'girls']", "['law', 'travels', 'cars']"]})

def solution(df):
    df["user_main_tag"] = df.apply(lambda x: x.str.replace(r"^\['(\w+)'.*", r"\g<1>", regex=True)["user_tags"], axis=1)
    return df


solution(initial_df)

user_name                   user_tags user_main_tag
0     Ivan 007    ['sport', 'law', 'cars']         sport
1     Petr 911    ['cars', 'law', 'girls']          cars
2  Nikolay 112  ['law', 'travels', 'cars']           law

## Некоторые значения в столбце FlightNumber отсутствуют. Значения в столбце должны увеличиваться на 10 с каждой строкой, поэтому в пропусках необходимо установить 10055 и 10075. Заполните эти недостающие числа и измените тип столбца с float на int

In [6]:
import pandas as pd
import numpy as np

initial_df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                                       'Budapest_PaRis', 'Brussels_londOn'],
                           'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
                           'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                           'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                                       '12. Air France', '"Swiss Air"']})

def solution(df):
    df["FlightNumber"] = df["FlightNumber"].interpolate().astype("int")
    return df


solution(initial_df)

From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris         10045      [23, 47]               KLM(!)
1      MAdrid_miLAN         10055            []    <Air France> (12)
2  londON_StockhOlm         10065  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis         10075          [13]       12. Air France
4   Brussels_londOn         10085      [67, 32]          "Swiss Air"

## Разбейте данные из столбца From_To на два столбца From и То. Исходный столбец удалите.

In [7]:
import pandas as pd
import numpy as np

def solution(df):
    df = pd.concat([df.drop(columns=["From_To"]),
                    df["From_To"].str.extract(r'(?P<From>.*?)_(?P<To>.*)').apply(lambda x: x.str.capitalize())], axis=1)
    return df


solution(initial_df)

FlightNumber  RecentDelays              Airline      From         To
0       10045.0      [23, 47]               KLM(!)    London      Paris
1           NaN            []    <Air France> (12)    Madrid      Milan
2       10065.0  [24, 43, 87]  (British Airways. )    London  Stockholm
3           NaN          [13]       12. Air France  Budapest      Paris
4       10085.0      [67, 32]          "Swiss Air"  Brussels     London

## В столбце Airline содержатся наименования авиакомпаний. Можно заметить, что в названиях присутствуют 'лишние' символы. Выполните преобразование столбца Airline:

In [8]:
import pandas as pd
import numpy as np

def solution(df):
    df["Airline"] = df["Airline"].replace(r'[^a-zA-Z\s]', '', regex=True).str.strip()
    return df


solution(initial_df)

From_To  FlightNumber  RecentDelays          Airline
0      LoNDon_paris       10045.0      [23, 47]              KLM
1      MAdrid_miLAN           NaN            []       Air France
2  londON_StockhOlm       10065.0  [24, 43, 87]  British Airways
3    Budapest_PaRis           NaN          [13]       Air France
4   Brussels_londOn       10085.0      [67, 32]        Swiss Air

## Распакуйте данные из RecentDelays по столбцам delay_1 ... delay_n. После распаковки удалите столбец RecentDelays.

In [9]:
import pandas as pd
import numpy as np

def solution(df):
    def foo(x):
        for i, v in enumerate(x):
            df.loc[x.name, f"delay_{i+1}"] = v

    df['RecentDelays'].explode().groupby(level=0).apply(foo)
    df = df.drop(columns='RecentDelays')
    return df


solution(initial_df)

From_To  FlightNumber          Airline  delay_1  delay_2  delay_3
0      LoNDon_paris       10045.0              KLM     23.0     47.0      NaN
1      MAdrid_miLAN           NaN       Air France      NaN      NaN      NaN
2  londON_StockhOlm       10065.0  British Airways     24.0     43.0     87.0
3    Budapest_PaRis           NaN       Air France     13.0      NaN      NaN
4   Brussels_londOn       10085.0        Swiss Air     67.0     32.0      NaN

## Замените на 0 все значения на диагоналях матрицы:

In [12]:
import pandas as pd
import numpy as np

initial_df = pd.DataFrame(np.random.RandomState(10).randint(1, 100, 100).reshape(10, -1))

def solution(df):
    dn = df.to_numpy()
    np.fill_diagonal(dn, 0)
    np.fill_diagonal(np.fliplr(dn), 0)
    return df


solution(initial_df)

0   1   2   3   4   5   6   7   8   9
0   0  16  65  29  90  94  30   9  74   0
1  41   0  17  12  55  89  63  34   0  79
2  50  52   0  78  70  14  26   0  93  87
3  31  31  90   0  66  32   0  37  28  19
4  94  78  23  24   0   0  29  75  89  10
5  16  19  81  72   0   0  18  47   8  76
6  29  34  85   0  89  45   0   5  72  89
7  89  51   0  35  16  78  89   0   7  86
8  23   0  13  93  97  63  58  80   0  58
9   0  51  46  41  90  74  38   1  19   0

## Создайте два новых столбца, один из которых является lag1 (сдвиг значений столбца А вниз на 1 строку), а другой — lead1 (сдвиг значений столбца B вверх на 1 строку):

In [14]:
import pandas as pd
import numpy as np

initial_df = pd.DataFrame(np.random.RandomState(10).randint(1, 100, 20).reshape(-1, 4), columns=list('abcd'))

def solution(df):
    df['a_lag1'] = df['a'].shift(1)
    df['b_lead1'] = df['b'].shift(-1)
    return df


solution(initial_df)

a   b   c   d  a_lag1  b_lead1
0  10  16  65  29     NaN     94.0
1  90  94  30   9    10.0      1.0
2  74   1  41  37    90.0     12.0
3  17  12  55  89    74.0     34.0
4  63  34  73  79    17.0      NaN

## В исходном датафрейме содержится информация о затратах во время командировок по каждому месяцу для каждого сотрудника. Выполните преобразование датафрейма:

In [15]:
import pandas as pd
import numpy as np

initial_df = pd.DataFrame({'city': ['Moscow', 'Berlin', 'Paris'], 'agent': [
                          'Ivan', 'Valter', 'Ali Abu'], 'Jan-2022': [5000, 3000, 2000], 'Feb-2022': [3000, 2000, 4000], 'March-2022': [0, 5000, 7000]})

def solution(df):
    df = df.melt(id_vars=['city', 'agent'], var_name='Date', value_name='Value')
    return df


solution(initial_df)

city    agent        Date  Value
0  Moscow     Ivan    Jan-2022   5000
1  Berlin   Valter    Jan-2022   3000
2   Paris  Ali Abu    Jan-2022   2000
3  Moscow     Ivan    Feb-2022   3000
4  Berlin   Valter    Feb-2022   2000
5   Paris  Ali Abu    Feb-2022   4000
6  Moscow     Ivan  March-2022      0
7  Berlin   Valter  March-2022   5000
8   Paris  Ali Abu  March-2022   7000

## Для каждого месяца определите, кто затратил больше всего денег:

In [25]:
import pandas as pd
import numpy as np

initial_df = pd.DataFrame({'city': ['Moscow', 'Berlin', 'Paris'], 'agent': ['Ivan', 'Valter', 'Ali Abu'], 'Jan-2022': [5000, 3000, 2000], 'Feb-2022': [
                          3000, 2000, 4000], 'March-2022': [0, 5000, 7000]}).melt(id_vars=["city", "agent"], var_name="Date", value_name="Value")

def solution(df):
    df = df.loc[df.groupby('Date').Value.idxmax()].sort_index()
    return df


solution(initial_df)

city    agent        Date  Value
0  Moscow     Ivan    Jan-2022   5000
5   Paris  Ali Abu    Feb-2022   4000
8   Paris  Ali Abu  March-2022   7000

## Сгруппируйте все затраты для каждого месяца в список:

In [27]:
import pandas as pd
import numpy as np

def solution(df):
    df = df.groupby('Date')['Value'].apply(list).reset_index(name='values_in_list')
    return df


solution(initial_df)

Date      values_in_list
0    Feb-2022  [3000, 2000, 4000]
1    Jan-2022  [5000, 3000, 2000]
2  March-2022     [0, 5000, 7000]

# 1.9

## В датафрейме содержатся классы ABC1 - ABC5. Постройте новый датафрейм, который будет состоять из уникальных пар классов:

In [29]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'class': ['ABC1', 'ABC2', 'ABC3', 'ABC4', 'ABC5'],
                   'base1': [1, 2, 3, 4, 5]})

def solution(df):

    df['key'] = 1
    df = df.merge(df, on='key', suffixes=('_1', '_2')).drop('key', axis=1)
    df = df.query('base1_1 < base1_2').set_index(['class_1', 'class_2'])

    return df


solution(df)

base1_1  base1_2
class_1 class_2                  
ABC1    ABC2           1        2
        ABC3           1        3
        ABC4           1        4
        ABC5           1        5
ABC2    ABC3           2        3
        ABC4           2        4
        ABC5           2        5
ABC3    ABC4           3        4
        ABC5           3        5
ABC4    ABC5           4        5

## В результате некоторой выездной проверки, контролёром Петренко была собрана информация о работающих магазинах (наименование, ИНН владельца, адрес магазина)[df_shops]:
![Image](https://ucarecdn.com/f21cfbef-561a-4c82-8c02-b4a814301312/)

Контролёр Петренко имеет доступ к базе разрешений на торговлю (номер разрешения, ИНН владельца, адрес торговли)[df_licenses]:

![Image](https://ucarecdn.com/05d1e139-152b-47eb-b4fa-d04c86458ab7/)

Помогите контролёру Петренко подтянуть информацию о разрешениях на торговлю в его датафрейм.

![Image](https://ucarecdn.com/9c2ec9c7-47b4-4d49-a82b-3c63e99b012f/)

Так получилось, что у Петренко нет информации о том, на какой конкретно магазин выдано разрешение (если по адресу у хозяина несколько магазинов). В таких случаях подтяните первое разрешение, которое ранее не было привязано.

В конечном счёте, на основе нашего датафрейма, Петренко построит сводную таблицу и поймет, где больше всего работает магазинов без разрешения на торговлю.

In [32]:
import pandas as pd
import numpy as np

df_shops = pd.DataFrame({
    'shop_name': ['Детские игрушки', 'Продукты', 'Хоз. товары', 'Бытовая химия', 'Военторг', 'АлкоМаркет', 'Фрукты-Овощи', 'Цветы 24'],
    'owner_inn': ['7700000001', '7700000001', '7700000002', '7700000002', '7700000003', '7700000004', '7700000005', '7700000006'],
    'address': ['ул. Академика Иванова, 1', 'ул. Академика Иванова, 1', 'ул. Летчиков, 5', 'ул. Летчиков, 5', 'ул. Автомобилистов, 6', 'ул. Автомобилистов, 6', 'ул. Первомайская, 66', 'ул. Степика, 123']})

df_licenses = pd.DataFrame({
    'reg_number': ['A-000-001', 'A-000-002', 'A-000-003', 'A-000-005', 'A-000-006', 'A-000-007'],
    'owner_inn': ['7700000001', '7700000001', '7700000002', '7700000003', '7700000004', '7700000005'],
    'address': ['ул. Академика Иванова, 1', 'ул. Академика Иванова, 1', 'ул. Летчиков, 5', 'ул. Автомобилистов, 6', 'ул. Автомобилистов, 8', 'ул. Первомайская, 66']})

def solution(shops, lics):
    shops['rank'] = shops.groupby('owner_inn').cumcount()
    lics['rank'] = lics.groupby('owner_inn').cumcount()
    return shops.merge(lics, how='left').drop('rank', axis=1).fillna('-')


solution(df_shops, df_licenses)

shop_name   owner_inn                   address reg_number
0  Детские игрушки  7700000001  ул. Академика Иванова, 1  A-000-001
1         Продукты  7700000001  ул. Академика Иванова, 1  A-000-002
2      Хоз. товары  7700000002           ул. Летчиков, 5  A-000-003
3    Бытовая химия  7700000002           ул. Летчиков, 5          -
4         Военторг  7700000003     ул. Автомобилистов, 6  A-000-005
5       АлкоМаркет  7700000004     ул. Автомобилистов, 6          -
6     Фрукты-Овощи  7700000005      ул. Первомайская, 66  A-000-007
7         Цветы 24  7700000006          ул. Степика, 123          -

## Для каждой группы определите номер уникального значения:

In [31]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'group': [1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2], 'value': [
                  'a', 'a', 'b', 'b', 'b', 'b', 'c', 'd', 'd', 'd', 'd', 'e']})

def solution(df):
    df['group_val_id'] = df.groupby('group')['value'].rank(method='dense').astype('int8')
    return df


solution(df)

group value  group_val_id
0       1     a             1
1       1     a             1
2       1     b             2
3       1     b             2
4       1     b             2
5       1     b             2
6       1     c             3
7       2     d             1
8       2     d             1
9       2     d             1
10      2     d             1
11      2     e             2

# 2.1 Numpy

## Создайте нулевой вектор размера 10.

In [2]:
import numpy as np

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Как узнать размер в памяти массива Z.

In [3]:
import numpy as np

Z = np.zeros((10, 10))
print(f"{Z.size*8} bytes")

800 bytes


## Создайте нулевой вектор размера 10, но пятое значение равно 1

In [4]:
import numpy as np
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## Создайте вектор со значениями в диапазоне от 10 до 20

In [5]:
import numpy as np
np.arange(10, 21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

## Разверните вектор Z (первый элемент становится последним, а последний первым)

In [7]:
import numpy as np

Z = np.arange(10)
np.flip(Z, axis=0)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Создайте матрицу 3x3 со значениями в диапазоне от 0 до 8. Используйте arange и reshape.

In [8]:
import numpy as np

np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Найдите индексы ненулевых элементов массива Z. Ответ представьте в виде одномерного массива.

In [9]:
import numpy as np

def solution(Z):
    M = Z.nonzero()
    return M


solution(Z)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),)

## Создайте единичную матрицу 3х3

In [10]:
import numpy as np

z = np.zeros(9).reshape(3, 3)
np.fill_diagonal(z, 1)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Найдите наименьшее и наибольшее значение массива Z

In [11]:
import numpy as np

Z = np.array([1, 2, 0, 0, 4, 0])

print(Z.min(), Z.max())

0 4


## Создайте матрицу размером 5х5, где по краям будут единицы, а в центре нули.

In [12]:
import numpy as np

z = np.ndarray(shape=(5, 5))
z.fill(1)
z[1:-1, 1:-1] = 0
print(z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# 2.2

## Создайте матрицу 5x5 со значениями 1,2,3,4 чуть ниже диагонали

In [13]:
import numpy as np

z = np.zeros((5, 5))
np.fill_diagonal(z[1:, :-1], np.arange(1, 5))
z.astype("int64")

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

## Создайте матрицу 8x8 и заполните ее в шахматном порядке.

In [14]:
import numpy as np

z = np.zeros((8, 8), dtype=int)
z[1::2, ::2] = 1
z[::2, 1::2] = 1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Нормализуйте матрицу Z

In [15]:
import numpy as np

Z = np.array([[1, 2, 3, 4, 5], [5, 4, 3, 2, 1], [1, 2, 3, 4, 5], [5, 4, 3, 2, 1]])
print((Z-Z.mean())/Z.std())

[[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
 [ 1.41421356  0.70710678  0.         -0.70710678 -1.41421356]
 [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
 [ 1.41421356  0.70710678  0.         -0.70710678 -1.41421356]]


## Выполните матричное умножение А и B

In [18]:
import numpy as np

A = np.ones((5, 3))
B = np.ones((3, 2))

np.dot(A, B)

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

## Выполните умножение на -1 те значения, которые больше 3, но меньше 8. 

In [17]:
import numpy as np

Z = np.arange(11)

print(np.where((Z > 3) & (Z < 8), -1 * Z, Z))

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


## Как найти общие значения между двумя массивами Z1 и Z2?

In [19]:
import numpy as np

Z1 = np.array([1, 2, 3, 4, 5])
Z2 = np.array([6, 7, 8, 9, 5, 4])

np.intersect1d(Z1, Z2)

array([4, 5])

## Вычислите ((A+B)*(-A/2)) без копирования массивов.

In [21]:
import numpy as np

A = np.ones(3)*1
B = np.ones(3)*2

np.multiply(np.add(A, B), np.divide(-A, 2))

array([-1.5, -1.5, -1.5])

## Создайте матрицу 5x5 со значениями строк в диапазоне от 0 до 4.

In [22]:
import numpy as np

np.ones((5, 5))*np.arange(5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

## Создайте вектор размера 10 со значениями в диапазоне от 0 до 1. (0 и 1 не должны входить)

In [23]:
import numpy as np

np.linspace(0, 1, num=11, endpoint=False)[-10:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

## Выполните сортировку массива Z

In [24]:
import numpy as np

Z = np.array([6, 9, 5, 7, 8, 4])

np.sort(Z)

array([4, 5, 6, 7, 8, 9])

# 2.4

## Проверьте, равны ли элементы массивов A и B в пределах допуска, который равен 1 (проверка на приблизительное равенство). 

In [25]:
import numpy as np

A = np.array([1, 2, 3, 4, 5])
B = np.array([2, 3, 4, 5, 6])

np.all(np.abs(A-B) <= 1)

np.True_

## Матрица Z размером 10x2, содержит декартовы координаты. Преобразуйте их в полярные координаты.

In [26]:
import numpy as np
Z = np.array([[0.64414354, 0.38074849],
              [0.66304791, 0.16365073],
              [0.96260781, 0.34666184],
              [0.99175099, 0.2350579],
              [0.58569427, 0.4066901],
              [0.13623432, 0.54413629],
              [0.51817635, 0.76685511],
              [0.93385014, 0.08970338],
              [0.19577126, 0.99419368],
              [0.2351805, 0.23898637]])

print(np.sqrt(Z[:, 1]**2+Z[:, 0]**2))
print(np.arctan2(Z[:, 1], Z[:, 0]))

[0.74825819 0.68294516 1.02312669 1.0192263  0.71304601 0.56093145
 0.92551255 0.93814859 1.01328548 0.33529741]
[0.53384421 0.24197957 0.34566872 0.23271877 0.60693925 1.32547133
 0.97655486 0.09576376 1.37636924 0.79342443]


## Замените максимальное значение массива на -1

In [28]:
import numpy as np
Z = np.array([1, 6, 3, 9, 3, 6, 7, 10, 3])

Z[np.argsort(Z)[-1]] = -1
Z

array([ 1,  6,  3,  9,  3,  6,  7, -1,  3])

## Имея массивы X и Y постройте матрицу Коши: C (Cij =1/(xi - yj))а затем посчитайте детерминант.

In [30]:
import numpy as np

X = np.arange(8)
Y = X + 0.5

print(np.linalg.det(1 / np.subtract.outer(X, Y)))

3638.163637117973


## Найдите ближайшее значение (к заданному скаляру v) в векторе Z?

In [32]:
import numpy as np

Z = np.arange(100)
v = 68.2139380784148

Z[np.abs(Z-v).argmin()]

np.int64(68)