## 2.1 Основные конструкции

### 1. Easy

In [2]:
a,b = int(input()), int(input())
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a % b)
print((a**10+b**10)**0.5)

4
5
9
-1
20
0.8
0
4
3288.4952485901513


### 2. Индекс массы тела
Напишите программу для вычисления и оценки индекса массы тела (ИМТ) человека. ИМТ показывает весит человек больше или меньше нормы для своего роста.

In [6]:
def solution(m,l):
    imt = m/(l**2)
    if 18.5<=imt<=25:
        return "Оптимальная масса"
    elif imt<18.5:
        return "Недостаточная масса"
    else:
        return "Избыточная масса"
    
solution(75, 1.8)

'Оптимальная масса'

### 3. Стоимость строки
Дана строка текста. Напишите программу для подсчета стоимости строки, исходя из того, что один любой символ (в том числе пробел) стоит 60 копеек.

In [18]:
def solution(s):
    price = 60*len(s)
    return f"{price // 100} р. {price % 100} коп."
solution("Я собираюсь сделать ему предложение, от которого он не сможет отказаться.")

'43 р. 80 коп.'

### 4. Количество слов
Дана строка, состоящая из слов, разделенных пробелами. Напишите программу, которая подсчитывает количество слов в этой строке.

In [1]:
print(len(input().split()))

Hello world
2


### 5.Зодиак
Китайский гороскоп назначает животным годы в 12-летнем цикле. Один 12-летний цикл показан в таблице ниже. Таким образом, 2012 год будет очередным годом дракона.

In [32]:
def solution(year):
    zodiak = [
        "Дракон", "Змея", "Лошадь", "Овца", "Обезьяна", "Петух", "Собака",
        "Свинья", "Крыса", "Бык", "Тигр", "Заяц"
    ]
    return zodiak[(year - 2000) % 12]


solution(1945)

'Петух'

### 6. Переворот числа
Дано пятизначное или шестизначное натуральное число. Напишите программу, которая изменит порядок его последних пяти цифр на обратный.

In [64]:
s="25000"
int(s.replace(s[-5:],s[:-6:-1]))

52

### 7. Standard American Convention
На вход программе подаётся натуральное число. Напишите программу, которая вставляет в заданное число запятые в соответствии со стандартным американским соглашением о запятых в больших числах.


In [71]:
print(f"{int(input()):,}")
    

 	  3724650756252
3,724,650,756,252


### 8. Задача Иосифа Флавия
n человек, пронумерованных числами от 1 до n, стоят в кругу. Они начинают считаться, каждый k-й по счету человек выбывает из круга, после чего счет продолжается со следующего за ним человека. Напишите программу, определяющую номер человека, который останется в кругу последним.

In [91]:
def F(n, k):
    return 1 if n == 1 else 1 + (F(n - 1, k) + k - 1) % n


F(2, 1)

2

## 2.2

### 1. Координатные четверти
Дан набор точек на координатной плоскости. Необходимо подсчитать и вывести количество точек, лежащих в каждой координатной четверти.

In [150]:
import numpy as np

def solution(n):
    test = '0 -1\n1 2\n0 9\n-9 -5'
    coords = np.array([x.split() for x in [_ for _ in test.splitlines()]], dtype=int)
    print("Первая четверть:", sum(np.logical_and(coords[:,0]>0, coords[:,1]>0)))
    print("Вторая четверть:", sum(np.logical_and(coords[:,0]<0, coords[:,1]>0)))
    print("Третья четверть:", sum(np.logical_and(coords[:,0]<0, coords[:,1]<0)))
    print("Четвертая четверть:", sum(np.logical_and(coords[:,0]>0, coords[:,1]<0)))
    
solution(4)

Первая четверть: 1
Вторая четверть: 0
Третья четверть: 1
Четвертая четверть: 0


### 2. Больше предыдущего
Напишите программу подсчета количества чисел, которые больше предшествующего им в этом списке числа, то есть, стоят вслед за меньшим числом. 

In [11]:
import numpy as np

print(sum(np.diff(np.array('1 2 3 4 5'.split(), dtype=int))>0))


4


### 3. Назад, вперёд и наоборот
На вход программе подается строка текста из натуральных чисел. Из элементов строки формируется список чисел. Напишите программу, которая меняет местами соседние элементы списка

In [18]:
import re

def solution(ls):
    regx = re.compile(r'(\d+)\s+(\d+)')
    return regx.sub(lambda m: f"{m.group(2)} {m.group(1)}", ls)

solution('1 2 3 4 5')

'2 1 4 3 5'

### 4. Сдвиг в развитии
Напишите программу циклического сдвига элементов списка направо, когда последний элемент становится первым, а остальные сдвигаются на одну позицию вперед, в сторону увеличения индексов.

In [23]:
from collections import deque

def solution(ls):
    dl = deque(ls.split())
    dl.rotate(1)
    return dl

print(*solution('489 483 43 2 3 84 1 4 3 2 5 4 3 13'))

13 489 483 43 2 3 84 1 4 3 2 5 4 3


### 5. Различные элементы
Напишите программу для подсчета количества разных элементов в списке.

In [26]:
len(set('2 2 5 5 5 5 8 10 10'.split()))

1

### 6. Произведение чисел
Напишите программу для определения, является ли число произведением двух чисел из данного набора, выводящую результат в виде ответа «ДА» или «НЕТ».

In [55]:
def solution(n):
    test = '89\n4\n77\n4'
    prod = 16
    nums = [int(x) for x in test.splitlines()]
    for i in range(len(nums)):
        for j in range(len(nums)):
            if i != j and nums[i] * nums[j] == prod:
                return "ДА"
    return "НЕТ"


solution(5)

'ДА'

### 7. Камень, ножницы, бумага
Программа должна вывести результат жеребьёвки, то есть кто победит

In [64]:
def solution(timur, ruslan):
    elems = {"камень": [0,1,-1], "ножницы": [-1,0,1], "бумага": [1,-1,0]}
    res = elems[timur][list(elems.keys()).index(ruslan)]
    return "Тимур" if res > 0 else "Руслан" if res < 0 else "ничья"
    
solution("камень", "ножницы") 

'Тимур'

In [63]:
def solution(timur, ruslan):
    var = ['камень', 'ножницы', 'бумага']
    ans = ['ничья', 'Руслан', 'Тимур']
    return ans[var.index(timur) - var.index(ruslan)]
    
solution("камень", "ножницы")       
    

'Тимур'

### 8. Камень, ножницы, бумага, ящерица, Спок
Правила игры стандартные: ножницы режут бумагу. Бумага заворачивает камень. Камень давит ящерицу, а ящерица травит Спока, в то время как Спок ломает ножницы, которые, в свою очередь, отрезают голову ящерице, которая ест бумагу, на которой улики против Спока. Спок испаряет камень, а камень, разумеется, затупляет ножницы.

In [95]:
def solution(timur, ruslan):
    graf = {
        'ножницы': ['бумага', 'ящерица'],
        'бумага': ['камень', 'Спок'],
        'камень': ['ножницы', 'ящерица'],
        'ящерица': ['Спок', 'бумага'],
        'Спок': ['ножницы', 'камень']
    }
    return "Тимур" if ruslan in graf[timur] else "Руслан" if timur in graf[ruslan] else "ничья"


solution("бумага", "Спок")

'Тимур'

In [97]:
#Алекс Глозман
def solution(timur, ruslan):
    g = ('ножницы', 'бумага', 'камень', 'ящерица', 'Спок')
    dist = (g.index(timur) - g.index(ruslan)) % len(g)
    return ('ничья', 'Тимур', 'Руслан')[dist and dist % 2 + 1]
            
solution("бумага", "Спок")


'Тимур'

### 9. Орел и решка
Дана строка текста, состоящая из букв русского алфавита "О" и "Р". Буква "О" – соответствует выпадению Орла, а буква "Р" – соответствует выпадению Решки. Напишите программу, которая подсчитывает наибольшее количество подряд выпавших Решек.

In [114]:
len(max('ООООООРРРОРОРРРРРРР'.split('О')))


7

### 10. Кремниевая долина
Искусственный интеллект Антон, созданный Гилфойлом, взломал сеть умных холодильников. Теперь он использует их в качестве серверов "Пегого дудочника". Помогите владельцу фирмы отыскать все зараженные холодильники.

Для каждого холодильника существует строка с данными, состоящая из строчных букв и цифр, и если в ней присутствует слово "anton" (необязательно рядом стоящие буквы, главное наличие последовательности букв), то холодильник заражен и нужно вывести номер холодильника, нумерация начинается с единицы

In [12]:
import re


def solution(n):
    test = [
        '222anton456', 'a1n1t1o1n1', '0000a0000n00t00000o000000n', 'gylfole',
        'richard', 'ant0n'
    ]
    rex = re.compile(r'a.*?n.*?t.*?o.*?n')
    fr = [i + 1 for i, s in enumerate(test) if rex.search(s) is not None]
    return fr


solution(9)

[1, 2, 3]

In [19]:
import re

print(*[
    i + 1 for i, s in enumerate([input() for _ in range(int(input()))])
    if re.search(r'a.*?n.*?t.*?o.*?n', s) is not None
])

6
222anton456
a1n1t1o1n1
0000a0000n00t00000o000000n
gylfole
richard
ant0n
1 2 3


### 11. Роскомнадзор запретил букву а
Необходимо написать программу, реализующую алгоритм написания [этой](https://www.youtube.com/watch?v=sAuMERnj-FU) песни. Алгоритм выводит в конце предложения следующую в алфавитном порядке букву, если она встречается в строке текста, а очередную строку отображает уже без этой буквы.

In [41]:
def solution(s):
    s = f"{s} запретил букву"
    for i in range(1072, 1104):
        if chr(i) in s:
            print(*s.split(), chr(i))
            s = s.replace(chr(i), '').strip()


solution('тимур')

тимур запретил букву а
тимур зпретил букву б
тимур зпретил укву в
тимур зпретил уку е
тимур зпртил уку з
тимур пртил уку и
тмур пртл уку к
тмур пртл уу л
тмур прт уу м
тур прт уу п
тур рт уу р
ту т уу т
у уу у


## 4.2 Вложенные списки
Дополните приведенный код так, чтобы он выводил единственное число: сумму всех чисел списка list1 разделённую на общее количество всех чисел.

In [89]:
def solution():
    list1 = [[1, 7, 8], [9, 7, 102], [102, 106, 105], [100, 99, 98, 103], [1, 2, 3]]
    total = sum(list1, [])
    return sum(total) / len(total)
solution()

53.3125

### Треугольник Паскаля
Треугольник Паскаля — бесконечная таблица биномиальных коэффициентов, имеющая треугольную форму. В этом треугольнике на вершине и по бокам стоят единицы. Каждое число равно сумме двух расположенных над ним чисел.

In [87]:
def pascal(n):
    res = []
    for i in range(n+1):
        res.append([1])
        for j in range(i):
            res[i].append(sum(res[i-1][j:j+2]))
    return res[:n]
    
[print(*li) for li in pascal(6)];

1
1 1
1 2 1
1 3 3 1
1 4 6 4 1
1 5 10 10 5 1


### Упаковка дубликатов
На вход программе подается строка текста, содержащая символы. Напишите программу, которая упаковывает последовательности одинаковых символов заданной строки в подсписки.

In [102]:
def solution(s):
    res = []
    for x in s.split():
        if res and x in res[-1]:
            res[-1].append(x)
        else:
            res.append([x])
    return res

solution('w w w o r l d g g g g r e a t t e c c h e m g g p w w')

[['w', 'w', 'w'],
 ['o'],
 ['r'],
 ['l'],
 ['d'],
 ['g', 'g', 'g', 'g'],
 ['r'],
 ['e'],
 ['a'],
 ['t', 't'],
 ['e'],
 ['c', 'c'],
 ['h'],
 ['e'],
 ['m'],
 ['g', 'g'],
 ['p'],
 ['w', 'w']]

### Разбиение на чанки
Реализуйте функцию chunked(), которая принимает на вход список и число, задающее размер чанка (куска), а возвращает список из чанков указанной длины.

In [132]:
def chunked(ls, size):
    ls = ls.split()
    return [ls[i:i+size] for i in range(0,len(ls),size)]


chunked('a b c d e f r g b ', 2)

[['a', 'b'], ['c', 'd'], ['e', 'f'], ['r', 'g'], ['b']]

### Подсписки списка
Подсписок может содержать один элемент, несколько, и даже ни одного. Например, [1], [2], [3] и [4] — подсписки списка [1, 2, 3, 4]. Список [2, 3] — подсписок списка [1, 2, 3, 4], но список [2, 4] не подсписок списка [1, 2, 3, 4], так как элементы 2 и 4 во втором списке не смежные. Пустой список — подсписок любого списка. Сам список — подсписок самого себя, то есть список [1, 2, 3, 4] подсписок списка [1, 2, 3, 4].

In [20]:
def chunked(ls, size):
    return [ls[i:i+size] for i in range(len(ls))]

def sublists(ls):
    ls = ls.split()
    res = [[]]    
    for i in range(len(ls)):
        for ch in chunked(ls, i+1):
            if len(ch) == i+1:
                res.append(ch)
    return res
sublists('1 2 3 1')

[[],
 ['1'],
 ['2'],
 ['3'],
 ['1'],
 ['1', '2'],
 ['2', '3'],
 ['3', '1'],
 ['1', '2', '3'],
 ['2', '3', '1'],
 ['1', '2', '3', '1']]

## 4.4 Матрицы

### Вывести матрицу

In [11]:
def sol(n,m):
    li = ['и','швец','и','жнец','и','на','дуде','игрец']    
#     li = [input() for _ in range(n*m)]
    [print(*li[i:i+m]) for i in range(0,n*m,m)]
        
sol(4,2)

и швец
и жнец
и на
дуде игрец


In [27]:
import numpy as np
def sol(n,m):
    mat = np.array(['и','швец','и','жнец','и','на','дуде','игрец']).reshape((n,m))
    [print(*r) for r in mat]
    print()
    [print(*r) for r in np.transpose(mat)]
        
sol(4,2)

и швец
и жнец
и на
дуде игрец

и и и дуде
швец жнец на игрец


### След матрицы
Следом квадратной матрицы называется сумма элементов главной диагонали. Напишите программу, которая выводит след заданной квадратной матрицы.

In [57]:
def sol(n):    
#     mat = list(map(int, [input().split() for _ in range(n)]))
    mat = list(map(lambda x: x.split(), ['1 2 3','4 5 6','7 8 9']))
    return sum(map(int, [mat[i][i] for i in range(n)]))

sol(3)
    

15

### Больше среднего
Напишите программу, которая выводит количество элементов квадратной матрицы в каждой строке, больших среднего арифметического элементов данной строки.

In [87]:
import numpy as np
def sol(n):    
#     mat = list(map(int, [input().split() for _ in range(n)]))
    mat = np.array(list(map(lambda x: x.split(), ['1 2 3 4','5 6 3 15','0 2 3 1', '5 2 8 5'])), dtype=int)
    print(mat)
    print(mat.mean(axis=1))
    return sum((np.transpose(mat)>mat.mean(axis=1)))

sol(3)

[[ 1  2  3  4]
 [ 5  6  3 15]
 [ 0  2  3  1]
 [ 5  2  8  5]]
[2.5  7.25 1.5  5.  ]


array([2, 1, 2, 1])

In [107]:
def sol(n):    
#     mat = list(map(int, [input().split() for _ in range(n)]))
    mat = list(map(lambda x: list(map(int, x.split())), ['1 2 3 4','5 6 3 15','0 2 3 1', '5 2 8 5']))
#     mat = [list(map(int, input().split())) for _ in range(n)]
    [print(sum([e>sum(r)/len(r) for e in r])) for r in mat]

sol(4)

2
1
2
1


### Максимальный в области


In [115]:
def sol(n):
    mat = list(map(lambda x: list(map(int, x.split())), ['1 4 5','6 7 8','1 1 6']))
    #     mat = [list(map(int, input().split())) for _ in range(n)]
    res = mat[0][0]
    for i in range(n):
        res = max(res, max(mat[i][:i+1]))
    return res

sol(3)
    

7

In [134]:
def sol(n):
    mat = list(map(lambda x: list(map(int, x.split())), ['1 4 5','6 7 8','1 1 6']))
    #     mat = [list(map(int, input().split())) for _ in range(n)]
    return max([mat[i][j] for j in range(n) for i in range(n) if n-j-1>=i>=j or j>=i>=n-j-1])

sol(3)

8

### Суммы четвертей
Квадратная матрица разбивается на четыре четверти, ограниченные главной и побочной диагоналями: верхнюю, нижнюю, левую и правую.
**Примечание.** Элементы диагоналей не учитываются.

In [149]:
def sol(n):
    mat = list(map(lambda x: list(map(int, x.split())), ['1 2 3 4','5 6 7 8','3 4 5 6', '1 2 3 4']))
    #     mat = [list(map(int, input().split())) for _ in range(n)]
    res = [0,0,0,0]
    keys = ['Верхняя четверть:', 'Правая четверть:', 'Нижняя четверть:', 'Левая четверть:']
    for i in range(n):
        for j in range(n):
            if n-j-1>i>j:
                res[3]+=mat[i][j]
            if j>i>n-j-1:
                res[1]+=mat[i][j]
            if n-j-1>i<j:
                res[0]+=mat[i][j]
            if n-j-1<i>j:
                res[2]+=mat[i][j]
        
    return dict(zip(keys, res))

[print(k,v) for k,v in sol(4).items()];
    

Верхняя четверть: 5
Правая четверть: 14
Нижняя четверть: 5
Левая четверть: 8


### Таблица умножения
На вход программе подаются два натуральных числа n и m — количество строк и столбцов в матрице. Создайте матрицу mult размером n×m и заполните её таблицей умножения по формуле mult[i][j] = i * j

In [15]:
def mult(n, m):
    [print(*[str(i*j).ljust(3) for j in range(m)]) for i in range(n)]
    
mult(4, 6)

0   0   0   0   0   0  
0   1   2   3   4   5  
0   2   4   6   8   10 
0   3   6   9   12  15 


### Максимум в таблице
Напишите программу, которая находит индексы (строку и столбец) первого вхождения максимального элемента.

In [27]:
import numpy as np
def sol(n,m):
    mat = np.array(list(map(lambda x: x.split(), ['0 3 2 4','2 3 5 5','5 1 2 3'])), dtype=int)
    return np.unravel_index(np.argmax(mat), shape=mat.shape)

print(*sol(3,4))


1 2


### Обмен столбцов
Напишите программу, которая меняет местами столбцы в матрице.

In [34]:
import numpy as np
def sol(n,m):
    mat = np.array(list(map(lambda x: x.split(), ['11 12 13 14','21 22 23 24','31 32 33 34'])), dtype=int)
#     mat = np.array([input().split() for _ in range(n)], dtype=int)
    i ,j = 0, 1
    mat[:,i], mat[:,j] = mat[:,j].copy(), mat[:,i].copy()
    return mat

print(sol(3,4))

[[12 11 13 14]
 [22 21 23 24]
 [32 31 33 34]]


### Симметричная матрица
Напишите программу, которая проверяет симметричность квадратной матрицы относительно главной диагонали.

In [49]:
def sol(n):
    mat = list(map(lambda x: list(map(int, x.split())), ['0 1 2','1 2 7','2 3 4']))
    #     mat = [list(map(int, input().split())) for _ in range(n)]
    return 'YES' if all([mat[i][j] == mat[j][i] for j in range(len(mat)) for i in range(j)]) else 'NO'
sol(3)

'NO'

### Обмен диагоналей
Дана квадратная матрица чисел. Напишите программу, которая меняет местами элементы, стоящие на главной и побочной диагонали, при этом каждый элемент должен остаться в том же столбце (то есть в каждом столбце нужно поменять местами элемент на главной диагонали и на побочной диагонали).

In [59]:
def sol(n):
    mat = list(map(lambda x: list(map(int, x.split())), ['1 2 3','4 5 6','7 8 9']))
    #     mat = [list(map(int, input().split())) for _ in range(n)]
    for i in range(n):
        mat[i][i], mat[n-i-1][i] = mat[n-i-1][i], mat[i][i]
        
    return mat
[print(*_) for _ in sol(3)];

7 2 9
4 5 6
1 8 3


### Зеркальное отображение
Напишите программу, которая зеркально отображает её элементы относительно горизонтальной оси симметрии.

In [62]:
def sol(n):
    mat = list(map(lambda x: list(map(int, x.split())), ['1 2 3','4 5 6','7 8 9']))
    #     mat = [list(map(int, input().split())) for _ in range(n)]
    mat.reverse()
    return mat

[print(*_) for _ in sol(3)];

7 8 9
4 5 6
1 2 3


### Поворот матрицы
Напишите программу, которая поворачивает квадратную матрицу чисел на 90 по часовой стрелке.

In [112]:
import numpy as np
def sol(n):
    mat = np.array(list(map(lambda x: x.split(), ['1 2 3','4 5 6','7 8 9'])), dtype=int)
    #     mat = [list(map(int, input().split())) for _ in range(n)]
    return np.rot90(mat, k=3)

[print(*_) for _ in sol(3)];

7 4 1
8 5 2
9 6 3


In [1]:
def sol(n):
    mat = list(map(lambda x: list(map(int, x.split())), ['1 2 3','4 5 6','7 8 9']))
    #     mat = [list(map(int, input().split())) for _ in range(n)]
    return [[mat[n-j-1][i] for j in range(n)] for i in range(n)]

[print(*_) for _ in sol(3)];

7 4 1
8 5 2
9 6 3


### Ходы коня
Напишите программу, которая отмечает положение коня на доске и все клетки, которые бьет конь. Клетку, где стоит конь, отметьте английской буквой N, клетки, которые бьет конь, отметьте символами *, остальные клетки заполните точками.

In [52]:
import math
def sol(ch):    
    j,i='abcdefgh'.index(ch[0]), 8-int(ch[1])
    chess = [['.' for _ in range(8)] for _ in range(8)]
    chess[i][j] = 'N'
    for f in range(12):
        x, y = round(math.sqrt(5)*math.cos(f*math.pi/6)), round(math.sqrt(5)*math.sin(f*math.pi/6))
        if x and y and x+i in range(8) and y+j in range(8):
            chess[x+i][y+j] = '*'
    
    return chess

[print(*_) for _ in sol('f3')];


. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . * . * .
. . . * . . . *
. . . . . N . .
. . . * . . . *
. . . . * . * .


### Магический квадрат
Магическим квадратом порядка n называется квадратная таблица размера n×n, составленная из всех чисел 1,2,3,…,n^2 так, что суммы по каждому столбцу, каждой строке и каждой из двух диагоналей равны между собой. Напишите программу, которая проверяет, является ли заданная квадратная матрица магическим квадратом.

In [81]:
import numpy as np


def sol(n):
    mat = np.array(
        list(map(lambda x: list(map(int, x.split())),['8 1 6', '3 5 7', '4 9 2']))
    )
    #     mat = [list(map(int, input().split())) for _ in range(n)]
    return 'YES' if np.unique(
        np.concatenate(
            (mat.sum(axis=0), mat.sum(axis=1),
             np.array(
                 (mat.diagonal().sum(),
                  np.rot90(mat, k=1).diagonal().sum()))))).size == 1 else 'NO'


sol(3)

'YES'

In [123]:
def sol(n):
    mat = list(map(lambda x: list(map(int, x.split())),['8 2 5', '2 5 8', '5 8 2']))
#     mat = [list(map(int, input().split())) for _ in range(n)]
    magic = n*(n**2 + 1) // 2
    diag=[0, 0]
    uniq = set()
    for i in range(n):
        diag[0] += mat[i][i]
        diag[1] += mat[i][n-i-1]
        uniq |= set(mat[i])
        if len(uniq) < n*(i+1) or not (sum(mat[i]) == magic and sum([mat[j][i] for j in range(n)]) == magic):
            return 'NO'
        
    return 'YES' if all([_ for _ in diag if _ == magic]) else 'NO'
            
    
sol(3)



'NO'

### Шахматная доска
Напишите программу для создания матрицы размером m x n заполнив ее символами . и * в шахматном порядке. В левом верхнем углу должна стоять точка.

In [62]:
def sol(nm):
    n,m = nm.split()
    return [['.*'[(i+j)%2] for j in range(int(m))] for i in range(int(n))]    
    
[print(*_) for _ in sol('3 4')];

. * . *
* . * .
. * . *


### Побочная диагональ
На вход программе подается натуральное число n. Напишите программу, которая создает матрицу размером n×n и заполняет её по следующему правилу:

- числа на побочной диагонали равны 1;
- числа, стоящие выше этой диагонали, равны 0;
- числа, стоящие ниже этой диагонали, равны 2.


In [69]:
def sol(n):
    return [[2 if j>n+~i else int(j==n+~i) for j in range(n)] for i in range(n)]
    
[print(*_) for _ in sol(6)];

0 0 0 0 0 1
0 0 0 0 1 2
0 0 0 1 2 2
0 0 1 2 2 2
0 1 2 2 2 2
1 2 2 2 2 2


### Заполнение
Напишите программу, которая создает матрицу размером n×m и заполняет её числами от 1 до n⋅m в соответствии с образцом.

In [80]:
def sol(nm):
    n,m = map(int, nm.split())
    return [[str(i*m+j+1).ljust(3) for j in range(m)] for i in range(n)] 

[print(*_) for _ in sol('4 7')];

1   2   3   4   5   6   7  
8   9   10  11  12  13  14 
15  16  17  18  19  20  21 
22  23  24  25  26  27  28 


In [10]:
def sol(nm):
    n,m = map(int, nm.split())
    return [[str(1+i+j*n).ljust(3) for j in range(m)] for i in range(n)] 

[print(*_) for _ in sol('6 6')];

1   7   13  19  25  31 
2   8   14  20  26  32 
3   9   15  21  27  33 
4   10  16  22  28  34 
5   11  17  23  29  35 
6   12  18  24  30  36 


In [13]:
def sol(n):
    return [[int(i==j or j==n+~i) for j in range(n)] for i in range(n)]
    
[print(*_) for _ in sol(5)];

1 0 0 0 1
0 1 0 1 0
0 0 1 0 0
0 1 0 1 0
1 0 0 0 1


In [26]:
def sol(n):
    return [[int(i<=j<=n+~i or i>=j>=n+~i) for j in range(n)] for i in range(n)]
    
[print(*_) for _ in sol(5)];

1 1 1 1 1
0 1 1 1 0
0 0 1 0 0
0 0 1 1 0
0 1 1 1 1


In [33]:
def sol(nm):
    n,m = map(int, nm.split())
    return [[str(1+(i+j+m)%m).ljust(3) for j in range(m)] for i in range(n)] 

[print(*_) for _ in sol('5 5')];

1   2   3   4   5  
2   3   4   5   1  
3   4   5   1   2  
4   5   1   2   3  
5   1   2   3   4  


In [56]:
def sol(nm):
    n,m = map(int, nm.split())
    return [[str(1+(i*m+j)).ljust(3) for j in range(m)][::(1,-1)[i%2]] for i in range(n)] 

[print(*_) for _ in sol('3 5')];

1   2   3   4   5  
10  9   8   7   6  
11  12  13  14  15 


In [210]:
def sol(nm):
    n,m = map(int, nm.split())
    mat=[[0]*m for _ in range(n)]
    c=0
    for d in range(n+m):
        for i in range(n):
            for j in range(m):
                if j==d+~i:
                    c+=1
                    mat[i][j] = str(c).ljust(3)
                
    return mat

[print(*_) for _ in sol('8 3')];

1   2   4  
3   5   7  
6   8   10 
9   11  13 
12  14  16 
15  17  19 
18  20  22 
21  23  24 


### Заполнение спиралью
Напишите программу, которая создает матрицу размером n×m заполнив её "спиралью" в соответствии с образцом.

In [31]:
import math
def sol(nm):
    n,m = map(int, nm.split())
    mat = [[0]*m for _ in range(n)]
    c = f = i = j = 0
    di, dj = 0, 1
    while c < n*m:
        if 0<=i<n and 0<=j<m and not mat[i][j]:
            c+=1
            mat[i][j] = str(c).ljust(3)
        else:            
            i += -di
            j += -dj
            f += math.pi/2
            di, dj = int(math.sin(f)), int(math.cos(f))
            
        i += di
        j += dj
            
    return mat

[print(*_) for _ in sol('6 6')];

1   2   3   4   5   6  
20  21  22  23  24  7  
19  32  33  34  25  8  
18  31  36  35  26  9  
17  30  29  28  27  10 
16  15  14  13  12  11 
